# Copyright 2025 Itential Inc. All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
----
get:
  use: accounts
  group: admin-essentials
  description: |
    Display one or more accounts

describe:
  use: account <name>
  group: admin-essentials
  description: |
    Display detailed information about an account
