# Copyright 2025 Itential Inc. All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
---
get:
  use: adapters
  group: admin-essentials
  description: |
    Display one or more adapters

describe:
  use: adapter <name>
  group: admin-essentials
  description: |
    Display detailed information about an adapter

create:
  use: adapter <name>
  group: admin-essentials

  hidden: true

  description: |
    Create a new adapter

    The `adapter create` command will create a new adapter on the target
    server.

delete:
  use: adapter <name>
  group: admin-essentials
  description: |
    Delete an existing adapter

copy:
  use: adapter <name> <dst>
  group: admin-essentials
  description: |
    Copy adapter configuration to another server

    The copy command will copy the specified adapter configuration from the
    source server to the destination server.

edit:
  use: adapter <name>
  group: admin-essentials
  description: |
    Edit an adapter configuration

import:
  use: adapter <name>
  group: admin-essentials
  description: |
    Import an adapter configuration

export:
  use: adapter <name>
  group: admin-essentials
  description: |
    Export an adapter configuration

load:
  use: adapters <path>
  group: admin-essentials
  description: |
    Load all adapters

dump:
  use: adapters
  group: admin-essentials
  description: |
    Dump all adapters

start:
  use: adapter <name>
  description: |
    Start a stopped adapter

stop:
  use: adapter <name>
  description: |
    Stop a running adapter

restart:
  use: adapter <name>
  description: |
    Restart an adapter

inspect:
  use: adapters
  description: |
    Show adapter status
