# Copyright 2025 Itential Inc. All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
----
get:
  use: adapter-models
  group: admin-essentials

  description: |
    Display one or more available adapter models

    The `get adapter-models` command will return the list of adapter models that
    are available on the server.

  example: |
    # Display list of adapter models
    4 ipctl get adapter-models
