---
get:
  use: analytic-templates
  group: automation-studio
  description: |
    Display one or more analytic-templates

describe:
  use: analytic-template <name>
  group: automation-studio
  description: |
    Display details about a analytic-template

create:
  use: analytic-template <name>
  group: automation-studio
  description: |
    Create a new analytic template

delete:
  use: analytic-template <name>
  group: automation-studio
  description: |
    Delete an analytic template

copy:
  use: analytic-template <name> --from <profile> --to <profile>
  group: automation-studio
  description: |
    Copy analytic template from one server to another

clear:
  use: analytic-templates
  group: automation-studio
  description: |
    Delete all configured analytic templates

import:
  use: analytic-template <path>
  group: automation-studio
  description: |
    Import an analytic template

export:
  use: analytic-template <name>
  group: automation-studio
  description: |
    Export an analytic template
