---
##############################################################################
# Reader Commands
##############################################################################
get:
  use: analytic-templates
  group: automation-studio
  description: |
    Display one or more analytic-templates

describe:
  use: analytic-template <name>
  group: automation-studio
  description: |
    Display details about a analytic-template

##############################################################################
# Writer Commands
##############################################################################

create:
  use: analytic-template <name>
  group: automation-studio
  description: |
    Create a new analytic template

delete:
  use: analytic-template <name>
  group: automation-studio
  description: |
    Delete an analytic template

copy:
  use: analytic-template <name> --from <profile> --to <profile>
  group: automation-studio
  description: |
    Copy analytic template from one server to another

clear:
  use: analytic-templates
  group: automation-studio
  description: |
    Delete all configured analytic templates


##############################################################################
# Promoter Commands
##############################################################################
import:
  use: analytic-template <path>
  group: automation-studio
  description: |
    Import an analytic template

export:
  use: analytic-template <name>
  group: automation-studio
  description: |
    Export an analytic template

##############################################################################
# Gitter Commands
##############################################################################
push:
  use: analytic-template <name> <repository>
  group: automation-studio
  description: |
    Push a command template to a repository

pull:
  use: analytic-template <filename> <repository>
  group: automation-studio
  description: |
    Pull a command template from a repository
