---
#############################################################################
# Inspector commands
#############################################################################

inspect:
  use: applications
  description: |
    Show application status
