---
#############################################################################
# Asset commands
#############################################################################
get:
  use: applications
  group: admin-essentials
  description: |
    Display one or more applications

describe:
  use: application <name>
  group: admin-essentials
  description: |
    Display detailed information about an application


#############################################################################
# Inspector commands
#############################################################################

inspect:
  use: applications
  description: |
    Show application status

start:
  use: application <name>
  description: |
    Start a stopped application

stop:
  use: application <name>
  description: |
    Stop a running application

restart:
  use: application <name>
  description: |
    Restart an application


