# Copyright 2025 Itential Inc. All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
---
get:
  use: configuration-parsers
  group: configuration-manager
  description: |
    Display one or more configuration parsers
