---
##############################################################################
# Reader commands
##############################################################################
#
get:
  use: configuration-parsers
  group: configuration-manager
  description: |
    Display one or more configuration parsers
