# Copyright 2025 Itential Inc. All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
---
load:
  use: load <path>
  description: |
    Load a dataset

dump:
  use: dump <path>
  description: |
    Dump a dataset.

    The dataset dump command will connect to the running instance of the Itential
    Platform and dump all of the configured assets into the specified path.

  example: |
    # Dump all assets to `assets`
    $ ipctl dump assets


