# Copyright 2025 Itential Inc. All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
---
get:
  use: devices
  group: configuration-manager
  description: |
    Display one or more devices

describe:
  use: device <name>
  group: configuration-manager
  description: |
    Display details about a device
