# Copyright 2025 Itential Inc. All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
----
get:
  use: device-groups
  group: configuration-manager
  description: |
    Display one or more device groups

describe:
  use: device-group <name>
  group: configuration-manager
  description: |
    Display details about a device group

create:
  use: device-group <name>
  group: configuration-manager
  description: |
    Create new device-group

delete:
  use: device-group <name>
  group: configuration-manager
  description: |
    Delete existing device-group

clear:
  use: device-groups
  group: configuration-manager
  description: |
    Delete all device-groups
