---
get:
  use: groups
  group: admin-essentials
  description: |
    Dispaly one or more groups

create:
  use: group <name>
  group: admin-essentials
  description: |
    Create a new group

delete:
  use: group <name>
  group: admin-essentials

  description: |
    Delete a group

    The `delete group <name>` command will delete a locally defined group in
    Itential Platform.  This command can only delete locally defined groups
    and will generate an error if the specified group name is not a local
    group.

  examples: |
    # Delete a group call admins
    $ ipctl delete group admin

describe:
  use: group <name>
  group: admin-essentials
  description: |
    Display details about a group

copy:
  use: group <name> --from <profile> --to <profile>
  group: admin-essentials

  description: |
    Copy a group from one server to another server

clear:
  use: groups
  group: admin-essentials
  description: |
    Delete all local groups

export:
  use: group <name>
  group: admin-essentials
  description: |
    Export a group

import:
  use: group <name>
  group: admin-essentials
  description: |
    Import a group

push:
  use: group <name> <repository>
  group: admin-essentials
  description: |
    Push a group to a repository

pull:
  use: group <filename> <repository>
  group: admin-essentials
  description: |
    Pull a group from a repository

