---
##############################################################################
# Reader Commands
##############################################################################

get:
  use: integration-models
  group: admin-essentials

  description: |
    Display one or more integration-models

    The `get integraion-models` will display the list of integration models
    that have been added to the server.

describe:
  use: integration-model <name>
  group: admin-essentials

  description: |
    Display detailed information about a integration-model

##############################################################################
# Writer Commands
##############################################################################

create:
  use: integration-model <path>
  group: admin-essentials

  description: |
    Create a new integration model

delete:
  use: integration-model <name>
  group: admin-essentials

  description: |
    Delete a integration-model

clear:
  use: integration-models
  group: admin-essentials

  description: |
    Delete all integration-models

##############################################################################
# Promoter Commands
##############################################################################
import:
  use: integration-model <path>
  group: admin-essentials

  description: |
    Import a integration-model package

export:
  use: integration-model <name>
  group: admin-essentials

  description: |
    Export a integration-model package
