# Copyright 2025 Itential Inc. All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
----
get:
  use: prebuilts
  group: admin-essentials

  description: |
    Display one or more prebuilts

describe:
  use: prebuilt <name>
  group: admin-essentials

  description: |
    Display detailed information about a prebuilt

delete:
  use: prebuilt <name>
  group: admin-essentials

  description: |
    Delete a prebuilt

clear:
  use: prebuilts
  group: admin-essentials

  description: |
    Delete all prebuilts

import:
  use: prebuilt <path>
  group: admin-essentials

  description: |
    Import a prebuilt package

export:
  use: prebuilt <name>
  group: admin-essentials

  description: |
    Export a prebuilt package
