---
##############################################################################
# Asset commands
##############################################################################

get:
  use: profiles
  group: admin-essentials
  description: |
    Display one or more profiles

describe:
  use: profile <name>
  group: admin-essentials
  description: |
    Display detailed information about a profile

create:
  use: profile <name>
  group: admin-essentials
  description: |
    Create a new profile

delete:
  use: profile <name>
  group: admin-essentials
  description: |
    Delete an existing profile

copy:
  use: profile <name> --from <profile> --to <profile>
  group: admin-essentials

  description: |
    Copy a profile from one server to another

    The `copy profile` command can be used to directly copy a configured
    profile from one server to another.   This command has three required
    arguments.  The first argument is the name of the profile to copy and
    it must exist on the source server.  The `--from` argument accepts the
    name of a named profile from the configuration file and designates the
    source server.  The `--to` argument accepts the anem of a named profile
    from the configuration file and designates the destination server.

    This command will first check if a profile by the same name exists on the
    destination server.   If one does, an error is returned unless the
    `--replace` option is used.  If `--replace` is specified, the profile
    on the destination server is replace with the one from the source
    server.

  example: |
    # Copy `profile1` from `dev` to `stage`
    $ ipctl copy profile profile1 --from dev --to stage

    # Copy and replace `profile1` from `stage` to `prod`
    $ ipctl copy profile profile1 --from stage --to prod --replace

##############################################################################
# Import/Export commands
##############################################################################

import:
  use: profile <path>
  group: admin-essentials
  description: |
    Import a profile

export:
  use: profile <name>
  group: admin-essentials
  description: |
    Export a profile

##############################################################################
# Repository commands
##############################################################################

push:
  use: profile <name> <repository>
  group: admin-essentials
  description: |
    Push a profile to a repository

pull:
  use: profile <filename> <repository>
  group: admin-essentials
  description: |
    Pull a profile from a repository
