---
get:
  use: roles
  group: admin-essentials

  description: |
    Display one or more roles

    The `get roles` command will retrieve all of the configured roles from the
    server and display them in table format.   By default, the command will
    only display `Custom` roles and filter out all of the builtin roles.

    To see all roles including the built in ones, use the `--all` command line
    option.

  example: |
    # Display all "Custom" roles that have been configured
    $ ipctl get roles

    # Display all roles including builtin ones
    $ ipctl get roles --all

create:
  use: role <name>
  group: admin-essentials

  description: |
    Create a new role

    the `create role` command will add a new role to the server.  The
    commmand accepts a single argument `name` which uniquely identifies
    the role.  If the role name already exists, this command will return
    an error.

    When creating a new role, one or more allowed methods can be assigned
    to the role using the `--method` option.  The `--method` option accepts
    an argument in the form of `name=<value>,type=<value>`.  The `--method`
    option can be specified multiple times.

    To view a list of all available methods, use the `ipctl get methods`
    command.

  example: |
    # Create a new role called `operators`
    $ ipctl create role operators --description "Network operations"

    # Create a new role called `pe`
    $ ipctl create role pe --method name=getAdapter,type=Adapter --method name=getIntegration,type=Integrations




delete:
  use: role <name>
  group: admin-essentials

  description: |
    Delete a role

    The `delete role <name>` command is used to delete a custom role that has
    been configured on the server.  This command can only delete roles that
    are of type `Custom`.  It cannot delete builtin roles.

  example: |
    # Delete a custom role called admins
    $ ipctl delete role admins

describe:
  use: role <name>
  group: admin-essentials

  description: |
    Display detailed information about a role

    When using the describe command, the name argument can take one of type
    forms depending on what you are trying to accomplish.  The first form
    is to simply pass the name of the role you wish to see detailed
    information about.  The second form is <type>:<name>.

    For instance, assume you want to see detailed information about the
    adapters admin role.  In this case, you woud use Adapters:admin as the
    input value to the describe command.

  example: |
    # Describe a role called admins
    $ ipctl describe role admins

    # Describe the adapters admin role
    $ ipctl describe role Adapters:admin

clear:
  use: roles
  group: admin-essentials

  description: |
    Delete all configured roles

    The `clear roles` command will delete all custom configured roles from
    the server.  This is a destructive command that cannot be undone

  example: |
    # Delete all custom roles
    $ ipctl clear roles

copy:
  use: role <name> --from <profile> --to <profile>
  group: admin-essentials

  description: |
    Copy a role from one server to another server

import:
  use: role <path>
  group: admin-essentials

  description: |
    Import a role to the target server

    The `import role` command will attempt to import a role define in a
    JSON document.  The command accepts a single positional argument `path`
    which defines the relative or absolute path to the file to import.

  example: |
    # Import a role defined in `admin.json`
    $ ipctl import role admin.json

    # Import the `admin.json` from a Git repository
    $ ipctl import role roles/admin.json --repository https://github.com/itential

export:
  use: role <name>
  group: admin-essentials

  description: |
    Export a role from the target server
