# Copyright 2025 Itential Inc. All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
----
get:
  use: tags
  group: admin-essentials
  description: |
    Display one or more tags

describe:
  use: tag <name>
  group: admin-essentials
  description: |
    Display details about a tag

create:
  use: tag <name>
  group: admin-essentials
  description: |
    Create a new tag

delete:
  use: tag <name>
  group: admin-essentials
  description: |
    Delete an existing tag

clear:
  use: tags
  group: admin-essentials
  description: |
    Delete all configured tags

copy:
  use: tag <name> --from <profile> --to <profile>
  group: admin-essentials
  description: |
    Copy a tag from one server to another server

