# Copyright 2025 Itential Inc. All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
----
get:
  use: transformations
  group: automation-studio
  description: |
    Display one or more transformations

describe:
  use: transformation <name>
  group: automation-studio

  description: |
    Display details about a transformation

create:
  use: transformation <name>
  group: automation-studio
  description: |
    Create a transformation

delete:
  use: transformation <name>
  group: automation-studio
  description: |
    Delete a transformation

clear:
  use: transformations
  group: automation-studio
  description: |
    Delete all transformations

copy:
  use: transformation <name>
  group: automation-studio
  description: |
    Copy a transformation from source to destination

import:
  use: transformation <path>
  group: automation-studio
  description: |
    Import a transformation

export:
  use: transformation <name>
  group: automation-studio
  description: |
    Export a transformation
